FROM ruby:2.5.3-alpine
RUN mkdir /weedock
ENV ROOT="/weedock"
WORKDIR ${ROOT}
# 必要なパッケージのインストール
RUN apk add --no-cache --update build-base \
                                linux-headers \
                                git \
                                imagemagick\
                                mysql-client \
                                mysql-dev \
                                nodejs \
                                tzdata\
                                openssh \
                                build-base \
                                libxml2-dev \
                                libxslt-dev \
                                yarn \
                                curl-dev
COPY Gemfile ${ROOT}
COPY Gemfile.lock ${ROOT}
RUN bundle install
COPY . ${ROOT}