version: '3'
services:
  db:
    container_name: weedock_db
    image: mysql:5.7
    ports:
      - "4306:3306"
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/weedock
    ports:
      - "3000:3000"
    links:
      - db
    tty: true
    stdin_open: true

volumes:
  db-volume:
